import type { Metadata } from 'next'
import { StaticPageShell } from '@/components/static-page-shell'

export const metadata: Metadata = {
  title: 'Business Idea Questions, Answered',
  description:
    'How HadIdea validates your business idea, what a report includes, what it costs, and how the live research works — common questions answered honestly.',
}

// `plain` mirrors each JSX answer as plain text for the FAQPage JSON-LD below
// — structured data can't carry markup, and search/AI assistants quote it
// directly. Keep both in sync when editing an answer.
const FAQS: { q: string; a: React.ReactNode; plain: string }[] = [
  {
    q: 'What is HadIdea?',
    plain: "A tool that turns a raw business idea into a structured research report \u2014 competitors, costs, legal and compliance requirements, funding options, and prioritised next steps. You describe your idea in plain English; we do the research.",
    a: (
      <p>
        A tool that turns a raw business idea into a structured research report — competitors,
        costs, legal and compliance requirements, funding options, and prioritised next steps.
        You describe your idea in plain English; we do the research.
      </p>
    ),
  },
  {
    q: 'What do I get in a report?',
    plain: "A viability snapshot, real competitors found via live web search, a cost and profit breakdown, a legal and compliance checklist with official links, funding options, honest things to consider with how to handle each, and a prioritised checklist of next steps.",
    a: (
      <p>
        A viability snapshot, real competitors found via live web search, a cost and profit
        breakdown, a legal and compliance checklist with official links, funding options, honest
        &ldquo;things to consider&rdquo; (competitor density, costs, effort — named up front, each
        with how to handle it), and a prioritised checklist of next steps.
      </p>
    ),
  },
  {
    q: "What's the difference between the initial report and the full report?",
    plain: "The initial report gives you the headline picture \u2014 viability score and the shape of the opportunity \u2014 so you can decide whether to go deeper. The full report adds the complete detail: full competitor list with links, full cost breakdown, legal and compliance detail, and the complete next-steps plan.",
    a: (
      <p>
        The initial report gives you the headline picture — viability score and the shape of the
        opportunity — so you can decide whether to go deeper. The full report adds the complete
        detail: full competitor list with links, full cost breakdown, legal and compliance detail,
        and the complete next-steps plan.
      </p>
    ),
  },
  {
    q: 'How accurate is it?',
    plain: "Report content is generated by AI and grounded with live web search where possible. Competitor and source links are checked, but figures like cost estimates are AI estimates to validate against your own local numbers \u2014 the report tells you when something needs specialist verification rather than presenting a confident number it doesn't have.",
    a: (
      <p>
        Report content is generated by AI and grounded with live web search where possible.
        Competitor and source links are checked, but figures like cost estimates are AI
        estimates to validate against your own local numbers, not guarantees — the report tells
        you when something needs specialist verification (an accountant, a licensing body, an
        engineer) rather than presenting a confident number it doesn&apos;t have.
      </p>
    ),
  },
  {
    q: 'Who owns my idea?',
    plain: "You do \u2014 fully. We don't claim any rights over the ideas or answers you submit, and your ideas are never shared with other users or used to train models beyond generating your own report.",
    a: (
      <p>
        You do — fully. We don&apos;t claim any rights over the ideas or answers you submit, and
        your ideas are never shared with other users or used to train models beyond generating
        your own report.
      </p>
    ),
  },
  {
    q: 'What does it cost?',
    plain: "Pricing is still being finalised ahead of general availability. The final terms will be published on the Terms page before payment is required.",
    a: (
      <p>
        Pricing is still being finalised ahead of general availability. The final terms will be
        published on the{' '}
        <a href="/terms" className="text-indigo-300 underline hover:text-indigo-200 light:text-indigo-600 light:hover:text-indigo-700">
          Terms
        </a>{' '}
        page before payment is required.
      </p>
    ),
  },
  {
    q: 'How do refunds work?',
    plain: "Full refund if your report hasn't been generated yet, no questions asked. If a report is defective, we'll regenerate it or refund it in full — your choice. We don't offer change-of-mind refunds after a report is delivered, and nothing in our policy limits your rights under Australian Consumer Law. Details are in the Terms.",
    a: (
      <p>
        Full refund if your report hasn&apos;t been generated yet, no questions asked. If a report is
        defective, we&apos;ll regenerate it or refund it in full — your choice. We don&apos;t offer
        change-of-mind refunds after a report is delivered, and nothing in our policy limits your
        rights under Australian Consumer Law. The full policy is in the{' '}
        <a href="/terms" className="text-indigo-300 underline hover:text-indigo-200 light:text-indigo-600 light:hover:text-indigo-700">
          Terms
        </a>
        .
      </p>
    ),
  },
  {
    q: 'I have a problem with my purchase — how do I get help?',
    plain: "Head to the Support page, or contact us with the “Billing & refunds” option and the email you purchased with. Billing messages are flagged and handled first — charge problems are time-sensitive and we treat them that way.",
    a: (
      <p>
        Head to the{' '}
        <a href="/support" className="text-indigo-300 underline hover:text-indigo-200 light:text-indigo-600 light:hover:text-indigo-700">
          Support
        </a>{' '}
        page, or{' '}
        <a href="/contact?category=billing" className="text-indigo-300 underline hover:text-indigo-200 light:text-indigo-600 light:hover:text-indigo-700">
          contact us with the &ldquo;Billing &amp; refunds&rdquo; option
        </a>{' '}
        and the email you purchased with. Billing messages are flagged and handled first — charge
        problems are time-sensitive and we treat them that way.
      </p>
    ),
  },
  {
    q: 'Can I delete my data?',
    plain: "Yes. Deleting your account from account settings permanently erases your ideas, answers, and reports \u2014 there's no recovery after that.",
    a: (
      <p>
        Yes. Deleting your account from account settings permanently erases your ideas, answers,
        and reports — there&apos;s no recovery after that.
      </p>
    ),
  },
  {
    q: 'What kinds of ideas are supported?',
    plain: "Physical products, local services, software or apps, ecommerce brands, content or education businesses, marketplaces, and inventions.",
    a: (
      <ul className="mt-2 list-disc space-y-1 pl-5">
        <li>Physical products</li>
        <li>Local services</li>
        <li>Software or apps</li>
        <li>Ecommerce brands</li>
        <li>Content or education businesses</li>
        <li>Marketplaces</li>
        <li>Inventions</li>
      </ul>
    ),
  },
  {
    q: 'How long does a report take?',
    plain: "Typically a few minutes \u2014 generation runs in the background using live web research once you've answered the follow-up questions, and you don't need to keep the tab open.",
    a: (
      <p>
        Generation runs in the background once you&apos;ve answered the follow-up questions —
        typically a few minutes, since it involves live web research rather than a single AI call.
        You don&apos;t need to keep the tab open; the report is ready when you come back.
      </p>
    ),
  },
]

const FAQ_JSONLD = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQS.map(({ q, plain }) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: plain },
  })),
}

export default function FaqPage() {
  return (
    <StaticPageShell title="Frequently asked questions" intro="Facts, not marketing.">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(FAQ_JSONLD) }}
      />
      <div className="space-y-2">
        {FAQS.map((item, i) => (
          <details
            key={i}
            className="group rounded-lg border border-white/10 bg-slate-900/50 px-4 py-3 light:border-gray-200 light:bg-white"
          >
            <summary className="cursor-pointer list-none text-sm font-medium text-white marker:content-none light:text-gray-900">
              <span className="flex items-center justify-between gap-3">
                {item.q}
                <span className="shrink-0 text-slate-500 transition-transform group-open:rotate-45 light:text-gray-400" aria-hidden="true">
                  +
                </span>
              </span>
            </summary>
            <div className="mt-3 text-sm leading-relaxed text-slate-400 light:text-gray-600">{item.a}</div>
          </details>
        ))}
      </div>
    </StaticPageShell>
  )
}
