import type { Metadata } from 'next'
import { StaticPageShell } from '@/components/static-page-shell'

export const metadata: Metadata = {
  title: 'FAQ — HadIdea',
  description: 'Common questions about HadIdea, answered honestly.',
}

const FAQS: { q: string; a: React.ReactNode }[] = [
  {
    q: 'What is HadIdea?',
    a: (
      <p>
        A tool that turns a raw business idea into a structured research report — competitors,
        costs, legal and compliance requirements, funding options, and prioritised next steps.
        You describe your idea in plain English; we do the research.
      </p>
    ),
  },
  {
    q: 'What do I get in a report?',
    a: (
      <p>
        A viability snapshot, real competitors found via live web search, a cost and profit
        breakdown, a legal and compliance checklist with official links, funding options, honest
        &ldquo;things to consider&rdquo; (competitor density, costs, effort — named up front, each
        with how to handle it), and a prioritised checklist of next steps.
      </p>
    ),
  },
  {
    q: "What's the difference between the initial report and the full report?",
    a: (
      <p>
        The initial report gives you the headline picture — viability score and the shape of the
        opportunity — so you can decide whether to go deeper. The full report adds the complete
        detail: full competitor list with links, full cost breakdown, legal and compliance detail,
        and the complete next-steps plan.
      </p>
    ),
  },
  {
    q: 'How accurate is it?',
    a: (
      <p>
        Report content is generated by AI and grounded with live web search where possible.
        Competitor and source links are checked, but figures like cost estimates are AI
        estimates to validate against your own local numbers, not guarantees — the report tells
        you when something needs specialist verification (an accountant, a licensing body, an
        engineer) rather than presenting a confident number it doesn&apos;t have.
      </p>
    ),
  },
  {
    q: 'Who owns my idea?',
    a: (
      <p>
        You do — fully. We don&apos;t claim any rights over the ideas or answers you submit, and
        your ideas are never shared with other users or used to train models beyond generating
        your own report.
      </p>
    ),
  },
  {
    q: 'What does it cost?',
    a: (
      <p>
        Pricing is still being finalised ahead of general availability. The final terms will be
        published on the{' '}
        <a href="/terms" className="text-indigo-300 underline hover:text-indigo-200 light:text-indigo-600 light:hover:text-indigo-700">
          Terms
        </a>{' '}
        page before payment is required.
      </p>
    ),
  },
  {
    q: 'Can I delete my data?',
    a: (
      <p>
        Yes. Deleting your account from account settings permanently erases your ideas, answers,
        and reports — there&apos;s no recovery after that.
      </p>
    ),
  },
  {
    q: 'What kinds of ideas are supported?',
    a: (
      <ul className="mt-2 list-disc space-y-1 pl-5">
        <li>Physical products</li>
        <li>Local services</li>
        <li>Software or apps</li>
        <li>Ecommerce brands</li>
        <li>Content or education businesses</li>
        <li>Marketplaces</li>
        <li>Inventions</li>
      </ul>
    ),
  },
  {
    q: 'How long does a report take?',
    a: (
      <p>
        Generation runs in the background once you&apos;ve answered the follow-up questions —
        typically a few minutes, since it involves live web research rather than a single AI call.
        You don&apos;t need to keep the tab open; the report is ready when you come back.
      </p>
    ),
  },
]

export default function FaqPage() {
  return (
    <StaticPageShell title="Frequently asked questions" intro="Facts, not marketing.">
      <div className="space-y-2">
        {FAQS.map((item, i) => (
          <details
            key={i}
            className="group rounded-lg border border-white/10 bg-slate-900/50 px-4 py-3 light:border-gray-200 light:bg-white"
          >
            <summary className="cursor-pointer list-none text-sm font-medium text-white marker:content-none light:text-gray-900">
              <span className="flex items-center justify-between gap-3">
                {item.q}
                <span className="shrink-0 text-slate-500 transition-transform group-open:rotate-45 light:text-gray-400" aria-hidden="true">
                  +
                </span>
              </span>
            </summary>
            <div className="mt-3 text-sm leading-relaxed text-slate-400 light:text-gray-600">{item.a}</div>
          </details>
        ))}
      </div>
    </StaticPageShell>
  )
}
