import { createDbClient, createServiceClient } from '@/lib/db'
import { isAdminEmail } from '@/lib/admin'
import { logError } from '@/lib/log-error'
import { deriveHeadlineScore } from '@/lib/viability-score'
import { sanitizeSectionsForSample } from '@/lib/sample-report-clone'
import { NextResponse, type NextRequest } from 'next/server'

// Admin CRUD for sample_reports. The /app/admin layout gates the PAGE, but
// that gate does NOT protect this route — every admin API route re-checks
// isAdminEmail itself, per project ground rules. The service client is only
// ever created AFTER that check passes (matches src/app/api/admin/offers).

/** The acting admin's email on success, or a NextResponse to return as-is (401/403). */
async function requireAdmin(): Promise<{ email: string } | NextResponse> {
  const supabase = await createDbClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
  if (!isAdminEmail(user.email)) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  return { email: user.email! }
}

/**
 * Postgres 42P01 = undefined_table, PostgREST PGRST205 = "table not found in
 * schema cache" (what Supabase's REST layer actually returns in practice) —
 * either one means migration 011 hasn't run yet.
 */
function isMissingTable(error: { code?: string } | null | undefined): boolean {
  return error?.code === '42P01' || error?.code === 'PGRST205'
}

// ── List (incl. inactive) ────────────────────────────────────────────────
export async function GET(request: NextRequest) {
  const admin = await requireAdmin()
  if (admin instanceof NextResponse) return admin

  const url = new URL(request.url)
  if (url.searchParams.get('source') === 'reports') {
    return listSourceReports()
  }

  const service = createServiceClient()
  const { data, error } = await service
    .from('sample_reports')
    .select('id, title, archetype, restatement, headline_score, source_report_id, active, sort_order, created_at, updated_at')
    .order('sort_order', { ascending: true })

  if (error) {
    if (isMissingTable(error)) {
      return NextResponse.json({ samples: [], migrationMissing: true })
    }
    console.error('Error listing samples:', error)
    await logError({ source: 'api:admin/samples', message: `List samples failed: ${error.message}`, detail: error, path: 'GET /api/admin/samples' })
    return NextResponse.json({ error: 'Failed to load samples.' }, { status: 500 })
  }

  return NextResponse.json({ samples: data ?? [], migrationMissing: false })
}

// Recent completed FULL reports (sections has a competitors key), for the
// "create from report" picker. A report is only a candidate if it's the kind
// generated by the full-report pipeline, not a teaser-only one.
async function listSourceReports() {
  const service = createServiceClient()
  const { data, error } = await service
    .from('reports')
    .select('id, idea_id, status, sections, generation_completed_at, created_at, ideas(restatement, archetype)')
    .eq('status', 'complete')
    .order('generation_completed_at', { ascending: false, nullsFirst: false })
    .limit(50)

  if (error) {
    console.error('Error listing source reports:', error)
    await logError({ source: 'api:admin/samples', message: `List source reports failed: ${error.message}`, detail: error, path: 'GET /api/admin/samples?source=reports' })
    return NextResponse.json({ error: 'Failed to load reports.' }, { status: 500 })
  }

  type Row = {
    id: string
    idea_id: string
    sections: Record<string, unknown> | null
    generation_completed_at: string | null
    created_at: string
    ideas: { restatement: string | null; archetype: string } | { restatement: string | null; archetype: string }[] | null
  }

  const candidates = ((data ?? []) as Row[])
    .filter(r => r.sections && Array.isArray((r.sections as Record<string, unknown>).competitors))
    .slice(0, 25)
    .map(r => {
      const idea = Array.isArray(r.ideas) ? r.ideas[0] : r.ideas
      return {
        reportId: r.id,
        ideaId: r.idea_id,
        restatement: idea?.restatement ?? '(untitled idea)',
        archetype: idea?.archetype ?? 'other',
        completedAt: r.generation_completed_at ?? r.created_at,
      }
    })

  return NextResponse.json({ reports: candidates })
}

// ── Create from an existing report ───────────────────────────────────────
export async function POST(request: NextRequest) {
  const admin = await requireAdmin()
  if (admin instanceof NextResponse) return admin

  const body = await request.json().catch(() => ({}))
  const reportId = typeof body.reportId === 'string' ? body.reportId.trim() : ''
  const title = typeof body.title === 'string' ? body.title.trim() : ''
  if (!reportId) return NextResponse.json({ error: 'Missing reportId.' }, { status: 400 })
  if (!title) return NextResponse.json({ error: 'Title is required.' }, { status: 400 })

  const service = createServiceClient()
  const { data: report, error: reportError } = await service
    .from('reports')
    .select('id, sections, status, ideas(restatement, archetype)')
    .eq('id', reportId)
    .single()

  if (reportError || !report) {
    return NextResponse.json({ error: 'Source report not found.' }, { status: 404 })
  }
  if (report.status !== 'complete') {
    return NextResponse.json({ error: 'Source report is not complete.' }, { status: 400 })
  }

  const sections = (report.sections ?? {}) as Record<string, unknown>
  const idea = Array.isArray(report.ideas) ? report.ideas[0] : report.ideas
  const restatement = idea?.restatement
  const archetype = idea?.archetype
  if (!restatement || !archetype) {
    return NextResponse.json({ error: 'Source report is missing idea details.' }, { status: 400 })
  }

  const vs = sections.viability_snapshot as { scores?: Record<string, { score: number }> } | undefined
  const headlineScore = deriveHeadlineScore(vs?.scores ?? {})
  const sanitizedSections = sanitizeSectionsForSample(sections)

  const { data, error } = await service
    .from('sample_reports')
    .insert({
      title,
      archetype,
      restatement,
      sections: sanitizedSections,
      headline_score: headlineScore,
      source_report_id: reportId,
      active: false,
    })
    .select('id')
    .single()

  if (error) {
    if (isMissingTable(error)) {
      return NextResponse.json({ error: 'sample_reports table does not exist yet — run migration 011_sample_reports.sql.' }, { status: 409 })
    }
    console.error('Error creating sample:', error)
    await logError({ source: 'api:admin/samples', message: `Create sample failed: ${error.message}`, detail: error, path: 'POST /api/admin/samples' })
    return NextResponse.json({ error: 'Failed to create sample.' }, { status: 500 })
  }

  return NextResponse.json({ ok: true, id: data.id })
}
